config/routes.rb
Rails.application.routes.draw do
  resources :piadines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piadine.rb
class Piadine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/piadines_controller.rb
class PiadinesController < ApplicationController
  before_action :set_piadine, only: %i[ show edit update destroy ]

  # GET /piadines or /piadines.json
  def index
    @piadines = Piadine.all
  end

  # GET /piadines/1 or /piadines/1.json
  def show
  end

  # GET /piadines/new
  def new
    @piadine = Piadine.new
  end

  # GET /piadines/1/edit
  def edit
  end

  # POST /piadines or /piadines.json
  def create
    @piadine = Piadine.new(piadine_params)

    respond_to do |format|
      if @piadine.save
        format.html { redirect_to piadine_url(@piadine), notice: "Piadine was successfully created." }
        format.json { render :show, status: :created, location: @piadine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @piadine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piadines/1 or /piadines/1.json
  def update
    respond_to do |format|
      if @piadine.update(piadine_params)
        format.html { redirect_to piadine_url(@piadine), notice: "Piadine was successfully updated." }
        format.json { render :show, status: :ok, location: @piadine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @piadine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piadines/1 or /piadines/1.json
  def destroy
    @piadine.destroy

    respond_to do |format|
      format.html { redirect_to piadines_url, notice: "Piadine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piadine
      @piadine = Piadine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def piadine_params
      params.require(:piadine).permit(:Nome, :impasto, :farcitura, :quantità, :indirizzo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/piadines_helper.rb
module PiadinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piadineria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/piadines/_form.html.erb
<%= form_with(model: piadine) do |form| %>
  <% if piadine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piadine.errors.count, "error") %> prohibited this piadine from being saved:</h2>

      <ul>
        <% piadine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="mb-3">
    <%= form.label :nome, class: 'form-label' %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>

 <div class="mb-3">
    <%= form.label :impasto, class: 'form-label' %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>

 <div class="mb-3">
    <%= form.label :farcitura, class: 'form-label' %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>

 <div class="mb-3">
    <%= form.label :quantita, class: 'form-label' %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :indirizzo, class: 'form-label' %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>


<% end %>

app/views/piadines/edit.html.erb
<h1>Editing Piadine</h1>

<%= render 'form', piadine: @piadine %>

<%= link_to 'Show', @piadine %> |
<%= link_to 'Back', piadines_path %>

app/views/piadines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Piadines</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Impasto</th>
      <th>Farcitura</th>
      <th>Quantità</th>
      <th>Indirizzo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @piadines.each do |piadine| %>
      <tr>
        <td><%= piadine.Nome %></td>
        <td><%= piadine.impasto %></td>
        <td><%= piadine.farcitura %></td>
        <td><%= piadine.quantità %></td>
        <td><%= piadine.indirizzo %></td>
        <td><%= link_to 'Show', piadine %></td>
        <td><%= link_to 'Edit', edit_piadine_path(piadine) %></td>
        <td><%= link_to 'Destroy', piadine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piadine', new_piadine_path %>

app/views/piadines/new.html.erb
<h1>New Piadine</h1>

<%= render 'form', piadine: @piadine %>

<%= link_to 'Back', piadines_path %>

app/views/piadines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @piadine.Nome %>
</p>

<p>
  <strong>Impasto:</strong>
  <%= @piadine.impasto %>
</p>

<p>
  <strong>Farcitura:</strong>
  <%= @piadine.farcitura %>
</p>

<p>
  <strong>Quantità:</strong>
  <%= @piadine.quantità %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @piadine.indirizzo %>
</p>

<%= link_to 'Edit', edit_piadine_path(@piadine) %> |
<%= link_to 'Back', piadines_path %>